author:
  - name: Gesellschaft für Informatik
  - name: deRSE
  - name: Julian Dehne
    orcid: 0000-0001-9265-9619
    url: https://www.researchgate.net/profile/Julian-Dehne
    email: julian.dehne@gi.de
    website: https://juliandehne.github.io/
    affiliations:
      - name: Gesellschaft für Informatik
        address: Rosa-Luxemburg Platz Berlin
      - name: deRSE
  - name: Florian Goth
  - name: Jan Phillip Thiele
  - name: Anna-Lena Lambrecht

profile:
  default: website

